from pydantic import BaseModel, Field
from typing import List

class GeneratedFile(BaseModel):
    file_path: str = Field(..., description="Relative path of the file (e.g., 'tests/specs/basket.spec.ts')")
    content: str = Field(..., description="Complete content of the file")

class CodeGenerationOutput(BaseModel):
    files: List[GeneratedFile] = Field(..., description="List of files generated by the agent")
    description: str = Field(..., description="Brief summary of what was generated")
